// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVfP5PI4Y_jnuQyHig5OZUgIwrvckidHQ',
    appId: '1:11474159721:web:12366c2a128a7ece43faf8',
    messagingSenderId: '11474159721',
    projectId: 'bloommind-9e867',
    authDomain: 'bloommind-9e867.firebaseapp.com',
    storageBucket: 'bloommind-9e867.firebasestorage.app',
    measurementId: 'G-XH2QKB4MM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzML3ivYTdq7yMFhMyyeRGEWFv5zKH4RQ',
    appId: '1:11474159721:android:abadae5cb7620c9b43faf8',
    messagingSenderId: '11474159721',
    projectId: 'bloommind-9e867',
    storageBucket: 'bloommind-9e867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrLWO8XgCiLpjTG-akc8lCOzPP1-BIbs0',
    appId: '1:11474159721:ios:f86ca45093ef127943faf8',
    messagingSenderId: '11474159721',
    projectId: 'bloommind-9e867',
    storageBucket: 'bloommind-9e867.firebasestorage.app',
    iosBundleId: 'com.example.bloommind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrLWO8XgCiLpjTG-akc8lCOzPP1-BIbs0',
    appId: '1:11474159721:ios:f86ca45093ef127943faf8',
    messagingSenderId: '11474159721',
    projectId: 'bloommind-9e867',
    storageBucket: 'bloommind-9e867.firebasestorage.app',
    iosBundleId: 'com.example.bloommind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVfP5PI4Y_jnuQyHig5OZUgIwrvckidHQ',
    appId: '1:11474159721:web:4bbf0ad18c63b60043faf8',
    messagingSenderId: '11474159721',
    projectId: 'bloommind-9e867',
    authDomain: 'bloommind-9e867.firebaseapp.com',
    storageBucket: 'bloommind-9e867.firebasestorage.app',
    measurementId: 'G-PM3EP3L5NT',
  );
}
